apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pricelists.pricelist.cloud.chx
spec:
  group: pricelist.cloud.chx
  names:
    kind: Pricelist
    listKind: PricelistList
    plural: pricelists
    singular: pricelist
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
