apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pricelists.pricelist.chernand.io
spec:
  group: pricelist.chernand.io
  names:
    kind: Pricelist
    listKind: PricelistList
    plural: pricelists
    singular: pricelist
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
