apiVersion: v1
kind: ServiceAccount
metadata:
  name: pricelist-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pricelist-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - jobs
  - pricelists
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  - batch
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - jobs
  - pricelists
  - routes
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  - batch
  resourceNames:
  - pricelist-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - pricelist.chernand.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pricelist-operator-user
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - pricelist.chernand.io
  resources:
  - pricelists
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pricelist-operator
subjects:
- kind: ServiceAccount
  name: pricelist-operator
  namespace: pricelist-operator
roleRef:
  kind: ClusterRole
  name: pricelist-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pricelists.pricelist.chernand.io
spec:
  group: pricelist.chernand.io
  names:
    kind: Pricelist
    listKind: PricelistList
    plural: pricelists
    singular: pricelist
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricelist-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pricelist-operator
  template:
    metadata:
      labels:
        name: pricelist-operator
    spec:
      serviceAccountName: pricelist-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: quay.io/redhatworkshops/pricelist-operator:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: quay.io/redhatworkshops/pricelist-operator:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pricelist-operator"
      volumes:
        - name: runner
          emptyDir: {}
---
